### ISSUE TITLE
Support for networkx 2.2

### ISSUE THREAD

**Issue by carlwitt** [Kappa-Dev/ReGraph#5]
Networkx 2.2 and 1.11 are syntactically not compatible. I'm using the newer version and the ReGraph examples won't work. For instance 

```
import networkx as nx
from regraph.primitives import add_nodes_from
G = nx.Graph()
add_nodes_from(G, [1, (2, {"a": 1}), 3])
```
gives 

```
 File "test_graph_rewrite.py", line 23, in test_basics
    add_nodes_from(G, [1, (2, {"a": 1}), 3])
  File "regraph/primitives.py", line 79, in add_nodes_from
    add_node(graph, n)
  File "regraph/primitives.py", line 51, in add_node
    graph.node[node_id] = new_attrs
TypeError: 'NodeView' object does not support item assignment
```
The reason is that in the newer veresion of networkx `graph.node` gives a NodeView object. The errors can be fixed by downgrading to networkx 1.11 (e.g., by using`pip install regraph --upgrade`) but that breaks the rest of my codebase. Moving on to the current networkx version would be really great!

**Comment by eugeniashurko** [comment]
Thank you very much for you comment! We are aware of this issue and planning to move to the new version asap.

**Comment by eugeniashurko** [comment]
Hi, I started moving KAMI to the new version of NetworkX (see this branch https://github.com/Kappa-Dev/ReGraph/tree/regaph_v2 ). It is probably early to call it a stable version, but all the unit tests are passing, and running examples work.
