### ISSUE TITLE
Accessing loop variable outside of loop

### ISSUE THREAD

**Issue by SchulzFabian** [Kappa-Dev/ReGraph#6]
https://github.com/Kappa-Dev/ReGraph/blob/43e362da80fc839c36ca30c427d6c316a36d933c/regraph/utils.py#L963

When the following try fails 
```
try:
     for v in values:
         value_set.add(v)
except TypeError:
     value_set.add(v)
```

the exception causes an exception because the parameter 'v' is not assigned outside of the for-loop.

UnboundLocalError: local variable 'v' referenced before assignment

**Comment by eugeniashurko** [comment]
Thanks a lot for spotting!
