### ISSUE TITLE
Bug with updated data 

### ISSUE THREAD

**Issue by ThomasGuillardel** [Kappa-Dev/ReGraph#7]
When we update the data's node in python script, that doesn't replace the previous value but add the new one.

**Comment by eugeniashurko** [comment]
Could you, please, provide details on which function of ReGraph do you call exactly and the result you get

**Comment by ThomasGuillardel** [comment]
?I'm sorry i didn't check my mails earlier?. I'll do it now.

________________________________
De : Eugenia Oshurko <notifications@github.com>
Envoyé : mardi 14 mai 2019 13:12
À : Kappa-Dev/ReGraph
Cc : GUILLARDEL THOMAS p1612078; Author
Objet : Re: [Kappa-Dev/ReGraph] Bug with updated data (#7)


Could you, please, provide details on which function of ReGraph do you call exactly and the result you get

-

**Comment by ThomasGuillardel** [comment]
I called **add_nodes_from** and **inject_update_node_attrs** and we checked **set_nodes_attrs ** to see if it was updated
