### ISSUE TITLE
Creating NXGraph from existing Networkx graph

### ISSUE THREAD

**Issue by sergred** [Kappa-Dev/ReGraph#8]
The [NXGraph](https://github.com/Kappa-Dev/ReGraph/blob/master/regraph/backends/networkx/graphs.py#L25) constructor has the `incoming_graph_data=None` that is never used, it seems that constructing a new NXGraph from the existing networkx graph is currently not supported.

**Comment by eugeniashurko** [comment]
Thanks a lot for spotting, I have merged the PR
